[build]
  # Directory with the build output
  publish = "dist"
  
  # Build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"